package ch.zhaw.einhoerner.editor;

public class ExampleText {
    public static final String EXAMPLE_TEXT = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean odio enim, viverra eget hendrerit fermentum, vulputate et odio. Aenean accumsan, ligula in ullamcorper dictum, odio turpis tempor ligula, a finibus turpis enim vehicula elit. Sed pharetra eros ac mi blandit iaculis. Sed id purus vitae felis suscipit efficitur. Fusce quis volutpat quam, vel placerat quam. Aenean faucibus ipsum imperdiet consectetur pulvinar. Proin vel lorem malesuada, elementum neque vel, finibus purus. Curabitur blandit euismod purus vel maximus. In sollicitudin magna nisl, eget tempor arcu sollicitudin sit amet. Praesent bibendum venenatis sem quis ornare. Donec sodales tellus ac dolor finibus porta.\n" +
            "\n" +
            "Donec malesuada scelerisque erat sed volutpat. Fusce lobortis porttitor mauris, eu accumsan felis maximus quis. Praesent eu magna scelerisque, tristique urna ut, sollicitudin lorem. Vestibulum nec eleifend urna. Aliquam convallis eu orci suscipit aliquet. Nullam sodales, leo quis ultrices ullamcorper, nulla risus placerat arcu, venenatis faucibus lacus turpis sed turpis. Vestibulum gravida, sapien eget sodales pulvinar, felis nunc congue lacus, aliquet elementum lectus ipsum eget lectus. Maecenas id vulputate leo.\n" +
            "\n" +
            "Vivamus viverra, augue vel condimentum ultricies, orci leo convallis lorem, nec gravida nulla sapien nec tellus. Suspendisse ultrices ornare molestie. Maecenas tincidunt lacinia faucibus. Integer tristique eget turpis non faucibus. Fusce id congue diam. Maecenas molestie tempor lectus ut scelerisque. Duis pellentesque mauris eu tellus posuere, at dictum neque sodales.\n" +
            "\n" +
            "Nam eu tortor dictum, tincidunt lacus sit amet, rhoncus enim. Sed sodales mi nec tellus sodales tincidunt et nec urna. Sed vehicula augue vitae nunc eleifend, a pulvinar ipsum dictum. Proin nibh ligula, vulputate vitae enim ut, iaculis ullamcorper justo. Vestibulum orci risus, tristique nec libero ut, finibus bibendum massa. Cras condimentum enim vitae nibh finibus aliquam. Sed semper tellus ligula, vitae condimentum risus viverra sit amet. Quisque ante ex, maximus sit amet felis a, scelerisque consequat libero. Sed vitae lacus purus. Pellentesque sagittis, erat sed accumsan dapibus, libero turpis ultrices nibh, ut egestas justo nibh id nibh. Fusce quis nulla metus. Praesent pellentesque, ipsum eget placerat laoreet, felis tortor ultricies ipsum, at faucibus quam neque nec magna. Nulla tellus tellus, varius sit amet consequat quis, mattis eu felis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla tincidunt, arcu et posuere vestibulum, diam lacus aliquam quam, aliquet blandit turpis ex a odio.\n" +
            "\n" +
            "Donec lorem lorem, aliquam nec tincidunt vitae, vestibulum vitae erat. In vel dui at libero tincidunt venenatis. Maecenas ac nibh ut leo pellentesque viverra vitae et nisl. Praesent non nunc sit amet purus tincidunt commodo et sed libero. Nullam tincidunt vehicula tortor. Mauris egestas tortor lacus, id tristique quam posuere eget. Praesent pretium accumsan quam, eget sodales ipsum bibendum vel. Donec ac tortor in velit tempor elementum. Phasellus eget posuere eros. Pellentesque rutrum tellus at nibh vulputate mollis. Aliquam lacinia arcu justo, vel scelerisque magna congue ac. Morbi gravida elit quam. Nulla sollicitudin, nunc ut elementum rhoncus, urna quam feugiat metus, a tincidunt ante ipsum at enim.";
}
